In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\Users\Sindhu\top-35-israeli-stocks-5-years-data.zip')

In [3]:
dataset

Date  Closing Price (0.01 NIS)  Change(%)  Opening  Price  \
0      22-02-2018                   17550.0       1.15         17440.0   
1      21-02-2018                   17350.0       3.09         16830.0   
2      20-02-2018                   16830.0       0.36         16720.0   
3      19-02-2018                   16770.0       2.51         16340.0   
4      18-02-2018                   16360.0      -1.09         16380.0   
5      15-02-2018                   16540.0      -2.93         17040.0   
6      14-02-2018                   17040.0      -0.76         17210.0   
7      13-02-2018                   17170.0      -2.11         17450.0   
8      12-02-2018                   17540.0       2.21         17160.0   
9      11-02-2018                   17160.0      -0.29         17210.0   
10     08-02-2018                   17210.0      -1.49         17400.0   
11     07-02-2018                   17470.0      -0.74         17600.0   
12     06-02-2018                   17600.0      -1.18         17440.0   
13     05-02-2018                   17810.0      -2.25         18230.0   
14     04-02-2018                   18220.0      -0.71         18150.0   
15     01-02-2018                   18350.0      -1.50         18630.0   
16     31-01-2018                   18630.0       4.02         17990.0   
17     30-01-2018                   17910.0      -1.16         18090.0   
18     29-01-2018                   18120.0      -2.42         18570.0   
19     28-01-2018                   18570.0       1.48         18300.0   
20     25-01-2018                   18300.0       0.60         18150.0   
21     24-01-2018                   18190.0      -0.38         18200.0   
22     23-01-2018                   18260.0      -0.44         18400.0   
23     22-01-2018                   18340.0       0.22         18450.0   
24     21-01-2018                   18300.0      -0.44         18200.0   
25     18-01-2018                   18380.0      -0.11         18490.0   
26     17-01-2018                   18400.0       0.66         18240.0   
27     16-01-2018                   18280.0      -1.30         18730.0   
28     15-01-2018                   18520.0      -1.59         18730.0   
29     14-01-2018                   18820.0       0.00         18990.0   
...           ...                       ...        ...             ...   
41399  11-04-2013                    1669.0       1.52          1665.0   
41400  10-04-2013                    1644.0       0.80          1630.0   
41401  09-04-2013                    1631.0      -0.37          1640.0   
41402  08-04-2013                    1637.0      -0.24          1641.0   
41403  07-04-2013                    1641.0      -0.12          1634.0   
41404  04-04-2013                    1643.0      -0.90          1658.0   
41405  03-04-2013                    1658.0      -0.24          1657.0   
41406  02-04-2013                    1662.0       0.85          1640.0   
41407  28-03-2013                    1648.0      -1.61          1655.0   
41408  27-03-2013                    1675.0      -0.18          1685.0   
41409  24-03-2013                    1678.0       2.19          1650.0   
41410  21-03-2013                    1642.0      -0.85          1660.0   
41411  20-03-2013                    1656.0      -0.90          1673.0   
41412  19-03-2013                    1671.0      -0.12          1673.0   
41413  18-03-2013                    1673.0       2.07          1628.0   
41414  17-03-2013                    1639.0       0.00          1647.0   
41415  14-03-2013                    1639.0      -0.97          1655.0   
41416  13-03-2013                    1655.0      -0.84          1654.0   
41417  12-03-2013                    1669.0      -0.60          1672.0   
41418  11-03-2013                    1679.0       0.54          1666.0   
41419  10-03-2013                    1670.0       1.46          1670.0   
41420  07-03-2013                    1646.0      -1.02          1650.0   
41421  06-03-2013

In [4]:
dataset['Symbol'].nunique()

35

In [5]:
dataset=dataset.drop("Symbol",axis=1)

In [6]:
dataset

Date  Closing Price (0.01 NIS)  Change(%)  Opening  Price  \
0      22-02-2018                   17550.0       1.15         17440.0   
1      21-02-2018                   17350.0       3.09         16830.0   
2      20-02-2018                   16830.0       0.36         16720.0   
3      19-02-2018                   16770.0       2.51         16340.0   
4      18-02-2018                   16360.0      -1.09         16380.0   
5      15-02-2018                   16540.0      -2.93         17040.0   
6      14-02-2018                   17040.0      -0.76         17210.0   
7      13-02-2018                   17170.0      -2.11         17450.0   
8      12-02-2018                   17540.0       2.21         17160.0   
9      11-02-2018                   17160.0      -0.29         17210.0   
10     08-02-2018                   17210.0      -1.49         17400.0   
11     07-02-2018                   17470.0      -0.74         17600.0   
12     06-02-2018                   17600.0      -1.18         17440.0   
13     05-02-2018                   17810.0      -2.25         18230.0   
14     04-02-2018                   18220.0      -0.71         18150.0   
15     01-02-2018                   18350.0      -1.50         18630.0   
16     31-01-2018                   18630.0       4.02         17990.0   
17     30-01-2018                   17910.0      -1.16         18090.0   
18     29-01-2018                   18120.0      -2.42         18570.0   
19     28-01-2018                   18570.0       1.48         18300.0   
20     25-01-2018                   18300.0       0.60         18150.0   
21     24-01-2018                   18190.0      -0.38         18200.0   
22     23-01-2018                   18260.0      -0.44         18400.0   
23     22-01-2018                   18340.0       0.22         18450.0   
24     21-01-2018                   18300.0      -0.44         18200.0   
25     18-01-2018                   18380.0      -0.11         18490.0   
26     17-01-2018                   18400.0       0.66         18240.0   
27     16-01-2018                   18280.0      -1.30         18730.0   
28     15-01-2018                   18520.0      -1.59         18730.0   
29     14-01-2018                   18820.0       0.00         18990.0   
...           ...                       ...        ...             ...   
41399  11-04-2013                    1669.0       1.52          1665.0   
41400  10-04-2013                    1644.0       0.80          1630.0   
41401  09-04-2013                    1631.0      -0.37          1640.0   
41402  08-04-2013                    1637.0      -0.24          1641.0   
41403  07-04-2013                    1641.0      -0.12          1634.0   
41404  04-04-2013                    1643.0      -0.90          1658.0   
41405  03-04-2013                    1658.0      -0.24          1657.0   
41406  02-04-2013                    1662.0       0.85          1640.0   
41407  28-03-2013                    1648.0      -1.61          1655.0   
41408  27-03-2013                    1675.0      -0.18          1685.0   
41409  24-03-2013                    1678.0       2.19          1650.0   
41410  21-03-2013                    1642.0      -0.85          1660.0   
41411  20-03-2013                    1656.0      -0.90          1673.0   
41412  19-03-2013                    1671.0      -0.12          1673.0   
41413  18-03-2013                    1673.0       2.07          1628.0   
41414  17-03-2013                    1639.0       0.00          1647.0   
41415  14-03-2013                    1639.0      -0.97          1655.0   
41416  13-03-2013                    1655.0      -0.84          1654.0   
41417  12-03-2013                    1669.0      -0.60          1672.0   
41418  11-03-2013                    1679.0       0.54          1666.0   
41419  10-03-2013                    1670.0       1.46          1670.0   
41420  07-03-2013                    1646.0      -1.02          1650.0   
41421  06-03-2013

In [7]:
x1=dataset.iloc[0:9999,1:9]

In [8]:
x1

Closing Price (0.01 NIS)  Change(%)  Opening  Price  Base Price  \
0                      17550.0       1.15         17440.0     17350.0   
1                      17350.0       3.09         16830.0     16830.0   
2                      16830.0       0.36         16720.0     16770.0   
3                      16770.0       2.51         16340.0     16360.0   
4                      16360.0      -1.09         16380.0     16540.0   
5                      16540.0      -2.93         17040.0     17040.0   
6                      17040.0      -0.76         17210.0     17170.0   
7                      17170.0      -2.11         17450.0     17540.0   
8                      17540.0       2.21         17160.0     17160.0   
9                      17160.0      -0.29         17210.0     17210.0   
10                     17210.0      -1.49         17400.0     17470.0   
11                     17470.0      -0.74         17600.0     17600.0   
12                     17600.0      -1.18         17440.0     17810.0   
13                     17810.0      -2.25         18230.0     18220.0   
14                     18220.0      -0.71         18150.0     18350.0   
15                     18350.0      -1.50         18630.0     18630.0   
16                     18630.0       4.02         17990.0     17910.0   
17                     17910.0      -1.16         18090.0     18120.0   
18                     18120.0      -2.42         18570.0     18570.0   
19                     18570.0       1.48         18300.0     18300.0   
20                     18300.0       0.60         18150.0     18190.0   
21                     18190.0      -0.38         18200.0     18260.0   
22                     18260.0      -0.44         18400.0     18340.0   
23                     18340.0       0.22         18450.0     18300.0   
24                     18300.0      -0.44         18200.0     18380.0   
25                     18380.0      -0.11         18490.0     18400.0   
26                     18400.0       0.66         18240.0     18280.0   
27                     18280.0      -1.30         18730.0     18520.0   
28                     18520.0      -1.59         18730.0     18820.0   
29                     18820.0       0.00         18990.0     18820.0   
...                        ...        ...             ...         ...   
9969                     913.0      -0.38           922.9       916.5   
9970                     916.5      -0.37           924.0       919.9   
9971                     919.9       0.70           919.2       913.5   
9972                     913.5       0.61           910.0       908.0   
9973                     908.0      -0.33           911.0       911.0   
9974                     911.0      -1.30           924.7       923.0   
9975                     923.0       0.61           919.9       917.4   
9976                     917.4       0.26           920.0       915.0   
9977                     915.0      -0.76           918.0       922.0   
9978                     922.0       0.74           918.8       915.2   
9979                     915.2       2.37           900.0       894.0   
9980                     894.0      -0.33           902.0       897.0   
9981                     897.0      -0.99           904.5       906.0   
9982                     906.0       1.00           896.4       897.0   
9983                     897.0       0.00           901.0       897.0   
9984                     897.0      -1.07           906.7       906.7   
9985                     906.7      -0.42           905.5       910.5   
9986                     910.5       1.05           907.0       901.0   
9987                     901.0      -1.64           916.0       916.0   
9988                     916.0      -0.52           920.8       920.8   
9989                     920.8      -0.45           920.0       925.0   
9990                     925.0       0.99           920.0       915.9   
9991                     915.9      -0.49           920.4       

In [9]:
x2=dataset.iloc[0:9999,10:]

In [10]:
x2

Volume  Trans.  Index Adjusted No. of Shares (IANS)
0      259345    1484                         1.212728e+08
1      227319    1690                         1.212728e+08
2      189453     702                         1.212728e+08
3       97661    1107                         1.212728e+08
4       75962    1001                         1.212728e+08
5      375415    1799                         1.212728e+08
6      113124    1426                         1.212728e+08
7      120346    1288                         1.212728e+08
8      101624    1343                         1.212728e+08
9       34320     517                         1.212728e+08
10      97097     988                         1.212728e+08
11     103699    1386                         1.212728e+08
12     229941    1308                         1.212728e+08
13     154499    1750                         1.212728e+08
14      37199     532                         1.212728e+08
15     237503     819                         1.212728e+08
16     248532    1222                         1.212728e+08
17     113925    1348                         1.212728e+08
18      55226     859                         1.212728e+08
19      35241     400                         1.212728e+08
20     234781    1125                         1.212728e+08
21      61998     944                         1.212728e+08
22     124651    1389                         1.212728e+08
23     126532     933                         1.212728e+08
24     127778     573                         1.212728e+08
25     174824    1002                         1.212728e+08
26      47192     691                         1.212728e+08
27      83778     733                         1.212728e+08
28     111583     966                         1.212728e+08
29      22114     417                         1.212728e+08
...       ...     ...                                  ...
9969  1133867     775                         1.164017e+09
9970   732107     434                         1.164017e+09
9971  5342507    1065                         1.164017e+09
9972  3136225    1787                         1.164017e+09
9973  2500649    1289                         1.164017e+09
9974  1612138     915                         1.164017e+09
9975   905237     533                         1.164017e+09
9976  1410639     633                         1.164017e+09
9977  1359275     878                         1.164017e+09
9978  2585551    1149                         1.164017e+09
9979  3850576    1610                         1.164017e+09
9980   957765     527                         1.164017e+09
9981  4288506    1533                         1.164017e+09
9982  3119065    1815                         1.164017e+09
9983  3154908    1234                         1.164017e+09
9984  3782601    1619                         1.164017e+09
9985   816162     528                         1.164017e+09
9986  2072920     939                         1.164017e+09
9987  4058123    1737                         1.164017e+09
9988  2712947    1017                         1.164017e+09
9989  1730872     836                         1.164017e+09
9990  1274133     646                         1.164017e+09
9991  4823115    1479                         1.164017e+09
9992  1905865     764                         1.164017e+09
9993  5529471     704                         1.164017e+09
9994  6587451    1052                         1.164017e+09
9995  2881575    1439                         1.164017e+09
9996  1752288     915                         1.164017e+09
9997  2372961    1328                         1.164017e+09
9998  1043597     652                         1.164017e+09

[9999 rows x 3 columns]

In [11]:
y=dataset.iloc[0:9999,9]

In [12]:
y

0       45119324
1       38974624
2       31823061
3       16290735
4       12395932
5       62600896
6       19221846
7       20746492
8       17765629
9        5906612
10      16845905
11      18154720
12      40833312
13      27926485
14       6751949
15      43695232
16      45429019
17      20602339
18      10094559
19       6522844
20      42792293
21      11304631
22      22830645
23      23179192
24      23404314
25      32037450
26       8692517
27      15432279
28      20855401
29       4169363
          ...   
9969    10397577
9970     6753263
9971    49107702
9972    28690034
9973    22794369
9974    14799783
9975     8347958
9976    12953681
9977    12465242
9978    23821040
9979    35114794
9980     8587578
9981    38682821
9982    28006896
9983    28316521
9984    34114296
9985     7418932
9986    18796249
9987    36855385
9988    24875425
9989    15926643
9990    11742921
9991    44189477
9992    17529994
9993    50169983
9994    58477537
9995    25580787
9996    158745

In [13]:
x=pd.concat([x1,x2], axis=1)

In [14]:
x

Closing Price (0.01 NIS)  Change(%)  Opening  Price  Base Price  \
0                      17550.0       1.15         17440.0     17350.0   
1                      17350.0       3.09         16830.0     16830.0   
2                      16830.0       0.36         16720.0     16770.0   
3                      16770.0       2.51         16340.0     16360.0   
4                      16360.0      -1.09         16380.0     16540.0   
5                      16540.0      -2.93         17040.0     17040.0   
6                      17040.0      -0.76         17210.0     17170.0   
7                      17170.0      -2.11         17450.0     17540.0   
8                      17540.0       2.21         17160.0     17160.0   
9                      17160.0      -0.29         17210.0     17210.0   
10                     17210.0      -1.49         17400.0     17470.0   
11                     17470.0      -0.74         17600.0     17600.0   
12                     17600.0      -1.18         17440.0     17810.0   
13                     17810.0      -2.25         18230.0     18220.0   
14                     18220.0      -0.71         18150.0     18350.0   
15                     18350.0      -1.50         18630.0     18630.0   
16                     18630.0       4.02         17990.0     17910.0   
17                     17910.0      -1.16         18090.0     18120.0   
18                     18120.0      -2.42         18570.0     18570.0   
19                     18570.0       1.48         18300.0     18300.0   
20                     18300.0       0.60         18150.0     18190.0   
21                     18190.0      -0.38         18200.0     18260.0   
22                     18260.0      -0.44         18400.0     18340.0   
23                     18340.0       0.22         18450.0     18300.0   
24                     18300.0      -0.44         18200.0     18380.0   
25                     18380.0      -0.11         18490.0     18400.0   
26                     18400.0       0.66         18240.0     18280.0   
27                     18280.0      -1.30         18730.0     18520.0   
28                     18520.0      -1.59         18730.0     18820.0   
29                     18820.0       0.00         18990.0     18820.0   
...                        ...        ...             ...         ...   
9969                     913.0      -0.38           922.9       916.5   
9970                     916.5      -0.37           924.0       919.9   
9971                     919.9       0.70           919.2       913.5   
9972                     913.5       0.61           910.0       908.0   
9973                     908.0      -0.33           911.0       911.0   
9974                     911.0      -1.30           924.7       923.0   
9975                     923.0       0.61           919.9       917.4   
9976                     917.4       0.26           920.0       915.0   
9977                     915.0      -0.76           918.0       922.0   
9978                     922.0       0.74           918.8       915.2   
9979                     915.2       2.37           900.0       894.0   
9980                     894.0      -0.33           902.0       897.0   
9981                     897.0      -0.99           904.5       906.0   
9982                     906.0       1.00           896.4       897.0   
9983                     897.0       0.00           901.0       897.0   
9984                     897.0      -1.07           906.7       906.7   
9985                     906.7      -0.42           905.5       910.5   
9986                     910.5       1.05           907.0       901.0   
9987                     901.0      -1.64           916.0       916.0   
9988                     916.0      -0.52           920.8       920.8   
9989                     920.8      -0.45           920.0       925.0   
9990                     925.0       0.99           920.0       915.9   
9991                     915.9      -0.49           920.4       

In [15]:
x=pd.concat([x1,x2],axis=1).values

In [16]:
x

array([[ 1.75500000e+04,  1.15000000e+00,  1.74400000e+04, ...,
         2.59345000e+05,  1.48400000e+03,  1.21272760e+08],
       [ 1.73500000e+04,  3.09000000e+00,  1.68300000e+04, ...,
         2.27319000e+05,  1.69000000e+03,  1.21272760e+08],
       [ 1.68300000e+04,  3.60000000e-01,  1.67200000e+04, ...,
         1.89453000e+05,  7.02000000e+02,  1.21272760e+08],
       ...,
       [ 9.00200000e+02, -1.29000000e+00,  9.12000000e+02, ...,
         1.75228800e+06,  9.15000000e+02,  1.16401699e+09],
       [ 9.12000000e+02,  4.50000000e-01,  9.05000000e+02, ...,
         2.37296100e+06,  1.32800000e+03,  1.16401699e+09],
       [ 9.07900000e+02,  1.33000000e+00,  9.04000000e+02, ...,
         1.04359700e+06,  6.52000000e+02,  1.16401699e+09]])

In [17]:
x.shape

(9999, 11)

In [18]:
y=dataset.iloc[0:9999,9].values

In [19]:
y

array([45119324, 38974624, 31823061, ..., 15874581, 21658043,  9458995],
      dtype=int64)

In [20]:
y.shape

(9999,)

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 0)

## Adding Input,Hidden and Output layers

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(input_dim=11,init="random_uniform",output_dim=10)) 
model.add(Dense(init="random_uniform",output_dim=5)) 
model.add(Dense(init="random_uniform",output_dim=1)) 
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mse'])
model.fit(x_train,y_train,epochs=300,batch_size=32)


Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


C:\Users\Sindhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, units=10, kernel_initializer="random_uniform")`
  """
C:\Users\Sindhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=5, kernel_initializer="random_uniform")`
  
C:\Users\Sindhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  import sys


Instructions for updating:
Use tf.cast instead.
Epoch 1/300
7999/7999 [==============================] - 3s 318us/step - loss: 441465790541333.9375 - mean_squared_error: 441465790541333.9375
Epoch 2/300
7999/7999 [==============================] - 0s 36us/step - loss: 414233644614793.3125 - mean_squared_error: 414233644614793.3125
Epoch 3/300
7999/7999 [==============================] - 0s 38us/step - loss: 389042218253883.3750 - mean_squared_error: 389042218253883.3750
Epoch 4/300
7999/7999 [==============================] - 0s 40us/step - loss: 294384807108631.5000 - mean_squared_error: 294384807108631.5000
Epoch 5/300
7999/7999 [==============================] - 0s 45us/step - loss: 226762949518277.7500 - mean_squared_error: 226762949518277.7500
Epoch 6/300
7999/7999 [==============================] - 0s 36us/step - loss: 206827151988462.3125 - mean_squared_error: 206827151988462.3125
Epoch 7/300
7999/7999 [==============================] - 0s 37us/step - loss: 193350339789471.8125 

7999/7999 [==============================] - 0s 35us/step - loss: 151052775358238.6875 - mean_squared_error: 151052775358238.6875
Epoch 57/300
7999/7999 [==============================] - 0s 32us/step - loss: 152773032955054.4688 - mean_squared_error: 152773032955054.4688
Epoch 58/300
7999/7999 [==============================] - 0s 32us/step - loss: 152171698771303.0625 - mean_squared_error: 152171698771303.0625
Epoch 59/300
7999/7999 [==============================] - 0s 33us/step - loss: 155032530875961.0312 - mean_squared_error: 155032530875961.0312
Epoch 60/300
7999/7999 [==============================] - 0s 33us/step - loss: 152522002578085.7188 - mean_squared_error: 152522002578085.7188
Epoch 61/300
7999/7999 [==============================] - 0s 32us/step - loss: 152888895933686.1875 - mean_squared_error: 152888895933686.1875
Epoch 62/300
7999/7999 [==============================] - 0s 31us/step - loss: 150287847575296.4688 - mean_squared_error: 150287847575296.4688
Epoch 63/300

7999/7999 [==============================] - 0s 32us/step - loss: 149125558289938.6250 - mean_squared_error: 149125558289938.6250
Epoch 114/300
7999/7999 [==============================] - 0s 32us/step - loss: 149311491207372.3125 - mean_squared_error: 149311491207372.3125
Epoch 115/300
7999/7999 [==============================] - 0s 29us/step - loss: 152354812552244.3438 - mean_squared_error: 152354812552244.3438
Epoch 116/300
7999/7999 [==============================] - 0s 32us/step - loss: 150252716176230.0000 - mean_squared_error: 150252716176230.0000
Epoch 117/300
7999/7999 [==============================] - 0s 34us/step - loss: 152142502484384.5625 - mean_squared_error: 152142502484384.5625
Epoch 118/300
7999/7999 [==============================] - 0s 31us/step - loss: 150763275519226.0000 - mean_squared_error: 150763275519226.0000
Epoch 119/300
7999/7999 [==============================] - 0s 31us/step - loss: 151205090124229.6875 - mean_squared_error: 151205090124229.6875
Epoch 

Epoch 170/300
7999/7999 [==============================] - 0s 32us/step - loss: 151547089798465.7188 - mean_squared_error: 151547089798465.7188
Epoch 171/300
7999/7999 [==============================] - 0s 32us/step - loss: 152393566344473.2500 - mean_squared_error: 152393566344473.2500
Epoch 172/300
7999/7999 [==============================] - 0s 33us/step - loss: 151662499300421.7500 - mean_squared_error: 151662499300421.7500
Epoch 173/300
7999/7999 [==============================] - 0s 32us/step - loss: 150742524274906.3750 - mean_squared_error: 150742524274906.3750
Epoch 174/300
7999/7999 [==============================] - 0s 32us/step - loss: 150057725620768.3125 - mean_squared_error: 150057725620768.3125
Epoch 175/300
7999/7999 [==============================] - 0s 33us/step - loss: 149942023278893.6250 - mean_squared_error: 149942023278893.6250
Epoch 176/300
7999/7999 [==============================] - 0s 32us/step - loss: 150697878853071.5312 - mean_squared_error: 1506978788530

7999/7999 [==============================] - 0s 33us/step - loss: 150572517509392.6875 - mean_squared_error: 150572517509392.6875
Epoch 227/300
7999/7999 [==============================] - 0s 32us/step - loss: 153760134031830.3438 - mean_squared_error: 153760134031830.3438
Epoch 228/300
7999/7999 [==============================] - 0s 32us/step - loss: 151220132546941.2188 - mean_squared_error: 151220132546941.2188
Epoch 229/300
7999/7999 [==============================] - 0s 30us/step - loss: 149288342662169.9688 - mean_squared_error: 149288342662169.9688
Epoch 230/300
7999/7999 [==============================] - 0s 33us/step - loss: 150076081828888.1875 - mean_squared_error: 150076081828888.1875
Epoch 231/300
7999/7999 [==============================] - 0s 32us/step - loss: 151421280572439.1875 - mean_squared_error: 151421280572439.1875
Epoch 232/300
7999/7999 [==============================] - 0s 33us/step - loss: 150676846859377.3125 - mean_squared_error: 150676846859377.3125
Epoch 

7999/7999 [==============================] - 0s 32us/step - loss: 151247498729351.9062 - mean_squared_error: 151247498729351.9062
Epoch 283/300
7999/7999 [==============================] - 0s 37us/step - loss: 151227398788764.3750 - mean_squared_error: 151227398788764.3750
Epoch 284/300
7999/7999 [==============================] - 0s 42us/step - loss: 151428720381577.6875 - mean_squared_error: 151428720381577.6875
Epoch 285/300
7999/7999 [==============================] - 0s 41us/step - loss: 149248249783725.2500 - mean_squared_error: 149248249783725.2500
Epoch 286/300
7999/7999 [==============================] - 0s 37us/step - loss: 151694409182475.6562 - mean_squared_error: 151694409182475.6562
Epoch 287/300
7999/7999 [==============================] - 0s 33us/step - loss: 151466466898513.5000 - mean_squared_error: 151466466898513.5000
Epoch 288/300
7999/7999 [==============================] - 0s 31us/step - loss: 149723030651785.3438 - mean_squared_error: 149723030651785.3438
Epoch 

In [23]:
y_pred=model.predict(x_test)

In [24]:
y_pred

array([[21955462. ],
       [15329254. ],
       [ 4966884. ],
       ...,
       [22701704. ],
       [ 5750745.5],
       [ 4617323. ]], dtype=float32)

In [25]:
y_test

array([20602580,  4453408,  4376966, ...,  7263483,  4675110, 10639026],
      dtype=int64)

In [26]:
y_pred[25]


array([5363639.], dtype=float32)

In [27]:
y_test[25]

6215100

In [28]:
y_pred[100]

array([19036302.], dtype=float32)

In [29]:
y_test[100]

22498776

In [30]:
y_pred_single=model.predict(np.array([[16830,0.36,16720,16770,17000,16660,1.27E+08,20410206,189453,702,1.21E+08]]))
y_pred_single

array([[23976838.]], dtype=float32)

In [31]:
y_test_single=model.predict(np.array([[16830,0.36,16720,16770,17000,16660,1.27E+08,20410206,189453,702,1.21E+08]]))
y_test_single

array([[23976838.]], dtype=float32)